name: Publish mcfeshared package to GitHub Packages

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@ocean-network-express"
          cache: "yarn"
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: npx lerna bootstrap
      - run: npx lerna run build --scope="@ocean-network-express/mcfeshared"
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Bump Prod Version Graduate
        continue-on-error: true
        id: graduateRelease
        run: yarn lerna version --conventional-graduate --conventional-commits --yes
      - name: Bump Prod Version Fallback
        if: ${{ always() && steps.graduateRelease.outcome == 'failure'  }}
        run: |
          echo Falling back to non-graduate release due to https://github.com/lerna/lerna/issues/2532
          git stash
          yarn lerna version --conventional-commits --yes

      - run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
