name: Publish mcfeshared package to GitHub Packages

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./frontend

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@ocean-network-express"
          cache: "yarn"
      # - name: yarn install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install
      # - run: npx lerna bootstrap
      # - run: npx lerna run build --scope="@ocean-network-express/mcfeshared"
      - run: npm ci
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor}}@users.noreply.github.com"
      - run: npx lerna version patch --conventional-commits --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
